<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;

class RecipesTableSeeder extends Seeder
{
    public function run(): void
    {
        // sample data is generated by AI.
        $recipes = [
            [
                'user_id' => 1,
                'title' => 'Spaghetti Carbonara',
                'description' => 'Classic Italian pasta dish with eggs, cheese, pancetta, and pepper.',
                'ingredients' => "200g spaghetti\n2 large eggs\n100g pancetta\n50g pecorino cheese\nBlack pepper\nSalt",
                'instructions' => "1. Boil pasta in salted water\n2. Fry pancetta until crispy\n3. Beat eggs and cheese together\n4. Mix everything together\n5. Season with pepper",
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'image' => 'https://i.pinimg.com/1200x/a2/26/07/a226076c1498919907ff9596acfb0874.jpg',
            ],
            [
                'user_id' => 1,
                'title' => 'Chicken Stir Fry',
                'description' => 'Quick and healthy chicken stir fry with vegetables.',
                'ingredients' => "300g chicken breast\n2 bell peppers\n1 onion\n3 tbsp soy sauce\n2 cloves garlic\n1 tbsp oil",
                'instructions' => "1. Cut chicken into strips\n2. Chop vegetables\n3. Stir fry chicken until cooked\n4. Add vegetables and sauce\n5. Cook for 5 minutes",
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 3,
                'image' => 'https://i.pinimg.com/1200x/72/ac/21/72ac21e30e6fafe5041f7e62cb449138.jpg',
            ],
            [
                'user_id' => 2,
                'title' => 'Vegetable Curry',
                'description' => 'Creamy coconut vegetable curry.',
                'ingredients' => "1 can coconut milk\n2 carrots\n1 potato\n100g cauliflower\n2 tbsp curry paste\nRice to serve",
                'instructions' => "1. Chop all vegetables\n2. Fry curry paste\n3. Add coconut milk and vegetables\n4. Simmer for 20 minutes\n5. Serve with rice",
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'image' => 'https://i.pinimg.com/736x/96/1c/04/961c047c15d9ce5b5b68b0dc47b39a64.jpg',
            ],
            [
                'user_id' => 2,
                'title' => 'Chocolate Cake',
                'description' => 'Rich and moist chocolate cake.',
                'ingredients' => "200g flour\n200g sugar\n100g cocoa powder\n3 eggs\n200g butter\n1 tsp baking powder",
                'instructions' => "1. Mix dry ingredients\n2. Cream butter and sugar\n3. Add eggs one by one\n4. Fold in flour mixture\n5. Bake at 180°C for 30 minutes",
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 8,
                'image' => 'https://i.pinimg.com/736x/2b/b5/fd/2bb5fd2dd315895410ac15781cda716c.jpg',
            ],
            [
                'user_id' => 3,
                'title' => 'Greek Salad',
                'description' => 'Fresh and healthy Greek salad.',
                'ingredients' => "2 tomatoes\n1 cucumber\n1 red onion\n200g feta cheese\nOlives\nOlive oil\nOregano",
                'instructions' => "1. Chop all vegetables\n2. Crumble feta cheese\n3. Add olives\n4. Drizzle with olive oil\n5. Sprinkle oregano",
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'image' => 'https://i.pinimg.com/1200x/18/2c/06/182c06c96b8041a48af543f51b079c44.jpg',
            ],
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }
    }
}